import Head from "next/head";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import { useContext } from "react";
import { styled } from "@mui/material/styles";
import { TabContext } from "@/context/TabContext";
import { Typography } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { tabNumber } = useContext(TabContext);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
      </Head>
      <main>
        <Navbar />
        {tabNumber === 0 &&
        <Typography> HomePage </Typography>}
      </main>
    </>
  );
}
